/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("cs346.kotlin-application-conventions")
}

dependencies {
    testImplementation(kotlin("test"))
}

tasks.test {
    useJUnitPlatform()
}

application {
    // Define the main class for the application.
    mainClass.set("cs346.app.AppKt")
}
